apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitserver
spec:
  template:
    spec:
      initContainers:
        - name: transfer-file-ownership
          image: index.docker.io/sourcegraph/alpine-3.12:insiders@sha256:b9123b8537b9cc4d65d27cc5c71fd27da28436ffda1946af7a1b1d052b696786
          command: ["sh", "-c", "if [[ \"$(stat -c '%u' /data/repos)\" -ne 100 ]]; then chown -R 100:101 /data/repos; fi"]
          volumeMounts:
            - mountPath: /data/repos
              name: repos
          securityContext:
            runAsUser: 0
