apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
spec:
  template:
    spec:
      initContainers:
        - name: transfer-file-ownership
          image: index.docker.io/sourcegraph/alpine-3.12:insiders@sha256:b9123b8537b9cc4d65d27cc5c71fd27da28436ffda1946af7a1b1d052b696786
          command: ["sh", "-c", "chown -R 472:472 /var/lib/grafana"]
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-data
          securityContext:
            runAsUser: 0
