apiVersion: apps/v1
kind: Deployment
metadata:
  name: sourcegraph-frontend
spec:
  template:
    spec:
      initContainers:
        - name: transfer-cache
          image: index.docker.io/sourcegraph/alpine-3.12:insiders@sha256:b9123b8537b9cc4d65d27cc5c71fd27da28436ffda1946af7a1b1d052b696786
          command: ["sh", "-c", "if [[ \"$(stat -c '%u' /mnt/cache)\" -ne 100 ]]; then chown -R 100:101 /mnt/cache; fi"]
          volumeMounts:
          - mountPath: /mnt/cache
            name: cache-ssd
          securityContext:
            runAsUser: 0
        - name: migrator
